"""create detections table

Revision ID: 7f931a80ef9c
Revises: 
Create Date: 2026-07-26 17:44:16.076291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7f931a80ef9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('image_time', sa.DateTime(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('bbox_west', sa.Float(), nullable=False),
    sa.Column('bbox_south', sa.Float(), nullable=False),
    sa.Column('bbox_east', sa.Float(), nullable=False),
    sa.Column('bbox_north', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # GeoAlchemy2's spatial_index=True on the Geometry column already creates the
    # GiST index via its own DDL event when the table is created - an explicit
    # create_index here would duplicate it and fail.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detections')
    # ### end Alembic commands ###
